In [145]:
def karatsuba_multi(x, y):
    """
    compute product of two numbers x and y
    where they both are consist of the same
    length of digits.
    """
    n = len(str(x))
    if x<10 or y<10:
        return x*y
    else:
        split_idx = n//2
        rest = n - split_idx
        high1 = int(str(x)[:split_idx])
        low1 = int(str(x)[split_idx:])
        high2 = int(str(y)[:split_idx])
        low2 = int(str(y)[split_idx:])
        z2 = karatsuba_multi(high1, high2)
        z1 = karatsuba_multi( (low1 + high1), (low2 + high2))
        z0 = karatsuba_multi(low1, low2)
        return ( z2 * (10**(rest*2)) + (z1 - z0 - z2)* (10**rest) + z0 )

In [178]:
x = 314159
y = 271828

In [179]:
karatsuba_multi(x, y) - x*y

-1118700000

In [181]:
159 * 828

131652

In [182]:
import pandas as pd

In [195]:
lists = pd.read_csv('/Users/hn/Desktop/ParticipatingEmployersJune2018.csv')

In [203]:
lists[lists['City'] == 'Moscow']

Employer E-Verify    City State  \
897    1600 - Good Samaritan Society - Moscow Village       No  Moscow    ID   
27489              Alta Science and Engineering, Inc.       No  Moscow    ID   

       ZIP Code        Size  
897       83843  100 to 499  
27489     83843    20 to 99

In [198]:
lists.columns

Index(['Employer', 'E-Verify', 'City', 'State', 'ZIP Code', 'Size'], dtype='object')

In [9]:
import numpy as np
np.random.seed(10)
np.random.randn(1)

array([1.3315865])

In [10]:
import numpy as np

In [11]:
A = np.ones((3,3))

In [13]:
r1 = .8
r2 = .6
r3 = .2
A[0, 1] = r1
A[0, 2] = r2
A[1, 0] = r1
A[1, 2] = r1
A[2, 0] = r2
A[2, 1] = r1
A

array([[1. , 0.8, 0.6],
       [0.8, 1. , 0.8],
       [0.6, 0.8, 1. ]])

In [15]:
v = np.array([r1, r2, r3])
v

array([0.8, 0.6, 0.2])

In [18]:
W = np.linalg.solve(A, v)

In [28]:
5 * (1 - np.dot(W,v))

0.9375

In [36]:
44.44311347 +  4*( -.01320934)  - 8.53419032

35.85608579

In [5]:
import pylab
import calendar
import numpy as np
import pandas as pd
import seaborn as sn
from scipy import stats
import missingno as msno
from datetime import datetime
import matplotlib
import matplotlib.pyplot as plt
from scipy.stats import kendalltau
import warnings
matplotlib.style.use('ggplot')


In [9]:
a = np.random.randn(3,4,1)
b = np.random.randn(3,1,2)
c = np.random.randn(3,1,1)
d = c+a*b
d.shape

(3, 4, 2)

In [18]:
import matplotlib as plt

In [19]:
pd.options.mode.chained_assignment = None
warnings.filterwarnings("ignore")
%matplotlib inline

In [20]:
fig = plt.figure()
fig.subplots_adjust(hspace=.8, wspace=.6)

for ii in range(1,8):
    ax = fig.add_subplot(2,4,i)
    ax.text(.5, .5, str((2,i,3)), ha='center')

TypeError: 'module' object is not callable

In [21]:
def f1(x):
    return 1/(1+np.exp(-x))
def f2(x):
    return x * (1-x)

In [23]:
f2(f1(0))

0.25

In [4]:
import tensorflow as tf

In [5]:
a = tf.constant(2)
b = tf.constant(10)
c = tf.multiply(a,b)
print (c)

Tensor("Mul_1:0", shape=(), dtype=int32)


In [46]:
def f(x):
    l = []
    for i in range(1,x+1):
        if x%i ==0:
            l.append(i)
    return l
f(12)

[1, 2, 3, 4, 6, 12]

In [47]:
a = 'abcs'

In [48]:
a[::-1]

'scba'

In [49]:
6 % 3==0

True

In [53]:
.6/(.3 + (3./14))

1.1666666666666667

In [51]:
4/6

0.6666666666666666

In [52]:
7/12

0.5833333333333334

In [54]:
.3 + (3./14)



0.5142857142857142

In [55]:
75+60+40

175

In [56]:
175/300

0.5833333333333334